package com.example.myapplication.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import kotlin.random.Random

fun randomColorSchemes(): Array<ColorScheme> {
    var md_theme_light_surfaceTint = Color(0xFF6750A4)
    var md_theme_light_onErrorContainer = Color(0xFF410E0B)
    var md_theme_light_onError = Color(0xFFFFFFFF)
    var md_theme_light_errorContainer = Color(0xFFF9DEDC)
    var md_theme_light_onTertiaryContainer = Color(0xFF31111D)
    var md_theme_light_onTertiary = Color(0xFFFFFFFF)
    var md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
    var md_theme_light_tertiary = Color(0xFF7D5260)
    var md_theme_light_shadow = Color(0xFF000000)
    var md_theme_light_error = Color(0xFFB3261E)
    var md_theme_light_outline = Color(0xFF79747E)
    var md_theme_light_onBackground = Color(0xFF1C1B1F)
    var md_theme_light_background = Color(0xFFFFFBFE)
    var md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
    var md_theme_light_inverseSurface = Color(0xFF313033)
    var md_theme_light_onSurfaceVariant = Color(0xFF49454F)
    var md_theme_light_onSurface = Color(0xFF1C1B1F)
    var md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
    var md_theme_light_surface = Color(0xFFFFFBFE)
    var md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
    var md_theme_light_onSecondary = Color(0xFFFFFFFF)
    var md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
    var md_theme_light_secondary = Color(0xFF625B71)
    var md_theme_light_inversePrimary = Color(0xFFD0BCFF)
    var md_theme_light_onPrimaryContainer = Color(0xFF21005D)
    var md_theme_light_onPrimary = Color(0xFFFFFFFF)
    var md_theme_light_primaryContainer = Color(0xFFEADDFF)
    var md_theme_light_primary = Color(0xFF6750A4)
    
    var md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
    var md_theme_dark_onErrorContainer = Color(0xFFF2B8B5)
    var md_theme_dark_onError = Color(0xFF601410)
    var md_theme_dark_errorContainer = Color(0xFF8C1D18)
    var md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
    var md_theme_dark_onTertiary = Color(0xFF492532)
    var md_theme_dark_tertiaryContainer = Color(0xFF633B48)
    var md_theme_dark_tertiary = Color(0xFFEFB8C8)
    var md_theme_dark_shadow = Color(0xFF000000)
    var md_theme_dark_error = Color(0xFFF2B8B5)
    var md_theme_dark_outline = Color(0xFF938F99)
    var md_theme_dark_onBackground = Color(0xFFE6E1E5)
    var md_theme_dark_background = Color(0xFF1C1B1F)
    var md_theme_dark_inverseOnSurface = Color(0xFF313033)
    var md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
    var md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
    var md_theme_dark_onSurface = Color(0xFFE6E1E5)
    var md_theme_dark_surfaceVariant = Color(0xFF49454F)
    var md_theme_dark_surface = Color(0xFF1C1B1F)
    var md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
    var md_theme_dark_onSecondary = Color(0xFF332D41)
    var md_theme_dark_secondaryContainer = Color(0xFF4A4458)
    var md_theme_dark_secondary = Color(0xFFCCC2DC)
    var md_theme_dark_inversePrimary = Color(0xFF6750A4)
    var md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
    var md_theme_dark_onPrimary = Color(0xFF381E72)
    var md_theme_dark_primaryContainer = Color(0xFF4F378B)
    var md_theme_dark_primary = Color(0xFFD0BCFF)
    
    
    var seed = Color(0xFF6750A4)

    when(Random.nextInt(10)) {
        1 -> {
            md_theme_light_primary = Color(0xFF0057CD)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFD9E2FF)
            md_theme_light_onPrimaryContainer = Color(0xFF001946)
            md_theme_light_secondary = Color(0xFF585E71)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFDCE2F9)
            md_theme_light_onSecondaryContainer = Color(0xFF151B2C)
            md_theme_light_tertiary = Color(0xFF725572)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFFDD7FA)
            md_theme_light_onTertiaryContainer = Color(0xFF2A122C)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFEFBFF)
            md_theme_light_onBackground = Color(0xFF1B1B1F)
            md_theme_light_surface = Color(0xFFFEFBFF)
            md_theme_light_onSurface = Color(0xFF1B1B1F)
            md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
            md_theme_light_onSurfaceVariant = Color(0xFF44464F)
            md_theme_light_outline = Color(0xFF757780)
            md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
            md_theme_light_inverseSurface = Color(0xFF303034)
            md_theme_light_inversePrimary = Color(0xFFB0C6FF)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFF0057CD)

            md_theme_dark_primary = Color(0xFFB0C6FF)
            md_theme_dark_onPrimary = Color(0xFF002C70)
            md_theme_dark_primaryContainer = Color(0xFF00419D)
            md_theme_dark_onPrimaryContainer = Color(0xFFD9E2FF)
            md_theme_dark_secondary = Color(0xFFC0C6DC)
            md_theme_dark_onSecondary = Color(0xFF2A3042)
            md_theme_dark_secondaryContainer = Color(0xFF404659)
            md_theme_dark_onSecondaryContainer = Color(0xFFDCE2F9)
            md_theme_dark_tertiary = Color(0xFFE0BBDD)
            md_theme_dark_onTertiary = Color(0xFF412742)
            md_theme_dark_tertiaryContainer = Color(0xFF593D59)
            md_theme_dark_onTertiaryContainer = Color(0xFFFDD7FA)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF1B1B1F)
            md_theme_dark_onBackground = Color(0xFFE3E2E6)
            md_theme_dark_surface = Color(0xFF1B1B1F)
            md_theme_dark_onSurface = Color(0xFFE3E2E6)
            md_theme_dark_surfaceVariant = Color(0xFF44464F)
            md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
            md_theme_dark_outline = Color(0xFF8F9099)
            md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
            md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
            md_theme_dark_inversePrimary = Color(0xFF0057CD)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFFB0C6FF)


            seed = Color(0xFF0058CE)
        }
        2 -> {
            md_theme_light_primary = Color(0xFF00696B)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFF6FF6F9)
            md_theme_light_onPrimaryContainer = Color(0xFF002020)
            md_theme_light_secondary = Color(0xFF4A6363)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFCCE8E8)
            md_theme_light_onSecondaryContainer = Color(0xFF041F20)
            md_theme_light_tertiary = Color(0xFF4C5F7C)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFD4E3FF)
            md_theme_light_onTertiaryContainer = Color(0xFF061C36)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFAFDFC)
            md_theme_light_onBackground = Color(0xFF191C1C)
            md_theme_light_surface = Color(0xFFFAFDFC)
            md_theme_light_onSurface = Color(0xFF191C1C)
            md_theme_light_surfaceVariant = Color(0xFFDAE4E4)
            md_theme_light_onSurfaceVariant = Color(0xFF3F4949)
            md_theme_light_outline = Color(0xFF6F7979)
            md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
            md_theme_light_inverseSurface = Color(0xFF2D3131)
            md_theme_light_inversePrimary = Color(0xFF4CDADD)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFF00696B)

            md_theme_dark_primary = Color(0xFF4CDADD)
            md_theme_dark_onPrimary = Color(0xFF003738)
            md_theme_dark_primaryContainer = Color(0xFF004F51)
            md_theme_dark_onPrimaryContainer = Color(0xFF6FF6F9)
            md_theme_dark_secondary = Color(0xFFB0CCCC)
            md_theme_dark_onSecondary = Color(0xFF1B3435)
            md_theme_dark_secondaryContainer = Color(0xFF324B4C)
            md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E8)
            md_theme_dark_tertiary = Color(0xFFB4C8E9)
            md_theme_dark_onTertiary = Color(0xFF1D314C)
            md_theme_dark_tertiaryContainer = Color(0xFF354863)
            md_theme_dark_onTertiaryContainer = Color(0xFFD4E3FF)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF191C1C)
            md_theme_dark_onBackground = Color(0xFFE0E3E2)
            md_theme_dark_surface = Color(0xFF191C1C)
            md_theme_dark_onSurface = Color(0xFFE0E3E2)
            md_theme_dark_surfaceVariant = Color(0xFF3F4949)
            md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
            md_theme_dark_outline = Color(0xFF899392)
            md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
            md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
            md_theme_dark_inversePrimary = Color(0xFF00696B)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFF4CDADD)


            seed = Color(0xFF006A6C)
        }
        3 -> {
            md_theme_light_primary = Color(0xFF056E00)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFF99F981)
            md_theme_light_onPrimaryContainer = Color(0xFF012200)
            md_theme_light_secondary = Color(0xFF54634D)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFD7E8CD)
            md_theme_light_onSecondaryContainer = Color(0xFF121F0E)
            md_theme_light_tertiary = Color(0xFF386568)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFBCEBEE)
            md_theme_light_onTertiaryContainer = Color(0xFF002021)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFCFDF6)
            md_theme_light_onBackground = Color(0xFF1A1C18)
            md_theme_light_surface = Color(0xFFFCFDF6)
            md_theme_light_onSurface = Color(0xFF1A1C18)
            md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
            md_theme_light_onSurfaceVariant = Color(0xFF43483F)
            md_theme_light_outline = Color(0xFF73796E)
            md_theme_light_inverseOnSurface = Color(0xFFF1F1EB)
            md_theme_light_inverseSurface = Color(0xFF2F312D)
            md_theme_light_inversePrimary = Color(0xFF7DDC68)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFF056E00)

            md_theme_dark_primary = Color(0xFF7DDC68)
            md_theme_dark_onPrimary = Color(0xFF023A00)
            md_theme_dark_primaryContainer = Color(0xFF035300)
            md_theme_dark_onPrimaryContainer = Color(0xFF99F981)
            md_theme_dark_secondary = Color(0xFFBBCBB1)
            md_theme_dark_onSecondary = Color(0xFF263422)
            md_theme_dark_secondaryContainer = Color(0xFF3C4B37)
            md_theme_dark_onSecondaryContainer = Color(0xFFD7E8CD)
            md_theme_dark_tertiary = Color(0xFFA0CFD2)
            md_theme_dark_onTertiary = Color(0xFF003739)
            md_theme_dark_tertiaryContainer = Color(0xFF1E4D50)
            md_theme_dark_onTertiaryContainer = Color(0xFFBCEBEE)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF1A1C18)
            md_theme_dark_onBackground = Color(0xFFE2E3DC)
            md_theme_dark_surface = Color(0xFF1A1C18)
            md_theme_dark_onSurface = Color(0xFFE2E3DC)
            md_theme_dark_surfaceVariant = Color(0xFF43483F)
            md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC)
            md_theme_dark_outline = Color(0xFF8D9387)
            md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
            md_theme_dark_inverseSurface = Color(0xFFE2E3DC)
            md_theme_dark_inversePrimary = Color(0xFF056E00)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFF7DDC68)


            seed = Color(0xFF056F00)
        }
        4 -> {
            md_theme_light_primary = Color(0xFF765A00)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFFFDF95)
            md_theme_light_onPrimaryContainer = Color(0xFF251A00)
            md_theme_light_secondary = Color(0xFF6A5D3F)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFF3E1BB)
            md_theme_light_onSecondaryContainer = Color(0xFF231A04)
            md_theme_light_tertiary = Color(0xFF486548)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFCAEBC7)
            md_theme_light_onTertiaryContainer = Color(0xFF05210A)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFFFBFF)
            md_theme_light_onBackground = Color(0xFF1E1B16)
            md_theme_light_surface = Color(0xFFFFFBFF)
            md_theme_light_onSurface = Color(0xFF1E1B16)
            md_theme_light_surfaceVariant = Color(0xFFECE1CF)
            md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
            md_theme_light_outline = Color(0xFF7E7667)
            md_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
            md_theme_light_inverseSurface = Color(0xFF33302A)
            md_theme_light_inversePrimary = Color(0xFFEEC148)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFF765A00)

            md_theme_dark_primary = Color(0xFFEEC148)
            md_theme_dark_onPrimary = Color(0xFF3E2E00)
            md_theme_dark_primaryContainer = Color(0xFF594400)
            md_theme_dark_onPrimaryContainer = Color(0xFFFFDF95)
            md_theme_dark_secondary = Color(0xFFD6C5A0)
            md_theme_dark_onSecondary = Color(0xFF3A2F15)
            md_theme_dark_secondaryContainer = Color(0xFF51452A)
            md_theme_dark_onSecondaryContainer = Color(0xFFF3E1BB)
            md_theme_dark_tertiary = Color(0xFFAECFAC)
            md_theme_dark_onTertiary = Color(0xFF1B361D)
            md_theme_dark_tertiaryContainer = Color(0xFF314D32)
            md_theme_dark_onTertiaryContainer = Color(0xFFCAEBC7)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF1E1B16)
            md_theme_dark_onBackground = Color(0xFFE9E1D9)
            md_theme_dark_surface = Color(0xFF1E1B16)
            md_theme_dark_onSurface = Color(0xFFE9E1D9)
            md_theme_dark_surfaceVariant = Color(0xFF4D4639)
            md_theme_dark_onSurfaceVariant = Color(0xFFCFC5B4)
            md_theme_dark_outline = Color(0xFF989080)
            md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
            md_theme_dark_inverseSurface = Color(0xFFE9E1D9)
            md_theme_dark_inversePrimary = Color(0xFF765A00)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFFEEC148)


            seed = Color(0xFF775B00)
        }
        5 -> {
            md_theme_light_primary = Color(0xFFA53C00)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFFFDBCD)
            md_theme_light_onPrimaryContainer = Color(0xFF360F00)
            md_theme_light_secondary = Color(0xFF77574B)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFFFDBCD)
            md_theme_light_onSecondaryContainer = Color(0xFF2C160C)
            md_theme_light_tertiary = Color(0xFF675F30)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFF0E3A8)
            md_theme_light_onTertiaryContainer = Color(0xFF211C00)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFFFBFF)
            md_theme_light_onBackground = Color(0xFF201A18)
            md_theme_light_surface = Color(0xFFFFFBFF)
            md_theme_light_onSurface = Color(0xFF201A18)
            md_theme_light_surfaceVariant = Color(0xFFF5DED6)
            md_theme_light_onSurfaceVariant = Color(0xFF53433E)
            md_theme_light_outline = Color(0xFF85736D)
            md_theme_light_inverseOnSurface = Color(0xFFFBEEEA)
            md_theme_light_inverseSurface = Color(0xFF362F2C)
            md_theme_light_inversePrimary = Color(0xFFFFB597)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFFA53C00)

            md_theme_dark_primary = Color(0xFFFFB597)
            md_theme_dark_onPrimary = Color(0xFF591D00)
            md_theme_dark_primaryContainer = Color(0xFF7E2C00)
            md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCD)
            md_theme_dark_secondary = Color(0xFFE7BEAE)
            md_theme_dark_onSecondary = Color(0xFF442A20)
            md_theme_dark_secondaryContainer = Color(0xFF5D4034)
            md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCD)
            md_theme_dark_tertiary = Color(0xFFD3C78E)
            md_theme_dark_onTertiary = Color(0xFF373006)
            md_theme_dark_tertiaryContainer = Color(0xFF4F471B)
            md_theme_dark_onTertiaryContainer = Color(0xFFF0E3A8)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF201A18)
            md_theme_dark_onBackground = Color(0xFFEDE0DC)
            md_theme_dark_surface = Color(0xFF201A18)
            md_theme_dark_onSurface = Color(0xFFEDE0DC)
            md_theme_dark_surfaceVariant = Color(0xFF53433E)
            md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BA)
            md_theme_dark_outline = Color(0xFFA08D86)
            md_theme_dark_inverseOnSurface = Color(0xFF201A18)
            md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
            md_theme_dark_inversePrimary = Color(0xFFA53C00)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFFFFB597)


            seed = Color(0xFFA63D00)
        }
        6 -> {
            md_theme_light_primary = Color(0xFFAB2F4A)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFFFD9DC)
            md_theme_light_onPrimaryContainer = Color(0xFF400011)
            md_theme_light_secondary = Color(0xFF765659)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFFFD9DC)
            md_theme_light_onSecondaryContainer = Color(0xFF2C1518)
            md_theme_light_tertiary = Color(0xFF785830)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFFFDDB7)
            md_theme_light_onTertiaryContainer = Color(0xFF2A1700)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFFFBFF)
            md_theme_light_onBackground = Color(0xFF201A1B)
            md_theme_light_surface = Color(0xFFFFFBFF)
            md_theme_light_onSurface = Color(0xFF201A1B)
            md_theme_light_surfaceVariant = Color(0xFFF4DDDE)
            md_theme_light_onSurfaceVariant = Color(0xFF524344)
            md_theme_light_outline = Color(0xFF847374)
            md_theme_light_inverseOnSurface = Color(0xFFFBEEEE)
            md_theme_light_inverseSurface = Color(0xFF362F2F)
            md_theme_light_inversePrimary = Color(0xFFFFB2BB)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFFAB2F4A)

            md_theme_dark_primary = Color(0xFFFFB2BB)
            md_theme_dark_onPrimary = Color(0xFF670021)
            md_theme_dark_primaryContainer = Color(0xFF8B1534)
            md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DC)
            md_theme_dark_secondary = Color(0xFFE5BDC0)
            md_theme_dark_onSecondary = Color(0xFF43292C)
            md_theme_dark_secondaryContainer = Color(0xFF5C3F42)
            md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DC)
            md_theme_dark_tertiary = Color(0xFFE9BF8F)
            md_theme_dark_onTertiary = Color(0xFF442B07)
            md_theme_dark_tertiaryContainer = Color(0xFF5E411B)
            md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB7)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF201A1B)
            md_theme_dark_onBackground = Color(0xFFECE0E0)
            md_theme_dark_surface = Color(0xFF201A1B)
            md_theme_dark_onSurface = Color(0xFFECE0E0)
            md_theme_dark_surfaceVariant = Color(0xFF524344)
            md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C3)
            md_theme_dark_outline = Color(0xFF9F8C8D)
            md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
            md_theme_dark_inverseSurface = Color(0xFFECE0E0)
            md_theme_dark_inversePrimary = Color(0xFFAB2F4A)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFFFFB2BB)


            seed = Color(0xFFAC304B)
        }
        7 -> {
            md_theme_light_primary = Color(0xFF366A1C)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFB6F393)
            md_theme_light_onPrimaryContainer = Color(0xFF072100)
            md_theme_light_secondary = Color(0xFF55624C)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFD9E7CB)
            md_theme_light_onSecondaryContainer = Color(0xFF131F0D)
            md_theme_light_tertiary = Color(0xFF386666)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFBBEBEC)
            md_theme_light_onTertiaryContainer = Color(0xFF002020)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFDFDF5)
            md_theme_light_onBackground = Color(0xFF1A1C18)
            md_theme_light_surface = Color(0xFFFDFDF5)
            md_theme_light_onSurface = Color(0xFF1A1C18)
            md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
            md_theme_light_onSurfaceVariant = Color(0xFF43483E)
            md_theme_light_outline = Color(0xFF74796D)
            md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
            md_theme_light_inverseSurface = Color(0xFF2F312D)
            md_theme_light_inversePrimary = Color(0xFF9BD67A)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFF366A1C)

            md_theme_dark_primary = Color(0xFF9BD67A)
            md_theme_dark_onPrimary = Color(0xFF123800)
            md_theme_dark_primaryContainer = Color(0xFF1E5102)
            md_theme_dark_onPrimaryContainer = Color(0xFFB6F393)
            md_theme_dark_secondary = Color(0xFFBDCBB0)
            md_theme_dark_onSecondary = Color(0xFF283420)
            md_theme_dark_secondaryContainer = Color(0xFF3E4A35)
            md_theme_dark_onSecondaryContainer = Color(0xFFD9E7CB)
            md_theme_dark_tertiary = Color(0xFFA0CFCF)
            md_theme_dark_onTertiary = Color(0xFF003738)
            md_theme_dark_tertiaryContainer = Color(0xFF1E4E4E)
            md_theme_dark_onTertiaryContainer = Color(0xFFBBEBEC)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF1A1C18)
            md_theme_dark_onBackground = Color(0xFFE3E3DC)
            md_theme_dark_surface = Color(0xFF1A1C18)
            md_theme_dark_onSurface = Color(0xFFE3E3DC)
            md_theme_dark_surfaceVariant = Color(0xFF43483E)
            md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
            md_theme_dark_outline = Color(0xFF8D9286)
            md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
            md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
            md_theme_dark_inversePrimary = Color(0xFF366A1C)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFF9BD67A)


            seed = Color(0xFF1C4F00)
        }
        8 -> {
            md_theme_light_primary = Color(0xFF2655CB)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFDBE1FF)
            md_theme_light_onPrimaryContainer = Color(0xFF00164D)
            md_theme_light_secondary = Color(0xFF595E72)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFDDE1F9)
            md_theme_light_onSecondaryContainer = Color(0xFF161B2C)
            md_theme_light_tertiary = Color(0xFF745470)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFFFD6F7)
            md_theme_light_onTertiaryContainer = Color(0xFF2B122A)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFEFBFF)
            md_theme_light_onBackground = Color(0xFF1B1B1F)
            md_theme_light_surface = Color(0xFFFEFBFF)
            md_theme_light_onSurface = Color(0xFF1B1B1F)
            md_theme_light_surfaceVariant = Color(0xFFE2E1EC)
            md_theme_light_onSurfaceVariant = Color(0xFF45464F)
            md_theme_light_outline = Color(0xFF767680)
            md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
            md_theme_light_inverseSurface = Color(0xFF303034)
            md_theme_light_inversePrimary = Color(0xFFB5C4FF)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFF2655CB)

            md_theme_dark_primary = Color(0xFFB5C4FF)
            md_theme_dark_onPrimary = Color(0xFF00297B)
            md_theme_dark_primaryContainer = Color(0xFF003CAC)
            md_theme_dark_onPrimaryContainer = Color(0xFFDBE1FF)
            md_theme_dark_secondary = Color(0xFFC1C5DD)
            md_theme_dark_onSecondary = Color(0xFF2B3042)
            md_theme_dark_secondaryContainer = Color(0xFF414659)
            md_theme_dark_onSecondaryContainer = Color(0xFFDDE1F9)
            md_theme_dark_tertiary = Color(0xFFE2BBDB)
            md_theme_dark_onTertiary = Color(0xFF432740)
            md_theme_dark_tertiaryContainer = Color(0xFF5B3D57)
            md_theme_dark_onTertiaryContainer = Color(0xFFFFD6F7)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF1B1B1F)
            md_theme_dark_onBackground = Color(0xFFE4E2E6)
            md_theme_dark_surface = Color(0xFF1B1B1F)
            md_theme_dark_onSurface = Color(0xFFE4E2E6)
            md_theme_dark_surfaceVariant = Color(0xFF45464F)
            md_theme_dark_onSurfaceVariant = Color(0xFFC6C6D0)
            md_theme_dark_outline = Color(0xFF8F909A)
            md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
            md_theme_dark_inverseSurface = Color(0xFFE4E2E6)
            md_theme_dark_inversePrimary = Color(0xFF2655CB)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFFB5C4FF)


            seed = Color(0xFF5F87FF)
        }
        9 -> {
            md_theme_light_primary = Color(0xFFC0001F)
            md_theme_light_onPrimary = Color(0xFFFFFFFF)
            md_theme_light_primaryContainer = Color(0xFFFFDAD7)
            md_theme_light_onPrimaryContainer = Color(0xFF410004)
            md_theme_light_secondary = Color(0xFF775654)
            md_theme_light_onSecondary = Color(0xFFFFFFFF)
            md_theme_light_secondaryContainer = Color(0xFFFFDAD7)
            md_theme_light_onSecondaryContainer = Color(0xFF2C1514)
            md_theme_light_tertiary = Color(0xFF735B2E)
            md_theme_light_onTertiary = Color(0xFFFFFFFF)
            md_theme_light_tertiaryContainer = Color(0xFFFFDEA7)
            md_theme_light_onTertiaryContainer = Color(0xFF271900)
            md_theme_light_error = Color(0xFFBA1A1A)
            md_theme_light_errorContainer = Color(0xFFFFDAD6)
            md_theme_light_onError = Color(0xFFFFFFFF)
            md_theme_light_onErrorContainer = Color(0xFF410002)
            md_theme_light_background = Color(0xFFFFFBFF)
            md_theme_light_onBackground = Color(0xFF201A1A)
            md_theme_light_surface = Color(0xFFFFFBFF)
            md_theme_light_onSurface = Color(0xFF201A1A)
            md_theme_light_surfaceVariant = Color(0xFFF5DDDB)
            md_theme_light_onSurfaceVariant = Color(0xFF534342)
            md_theme_light_outline = Color(0xFF857371)
            md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
            md_theme_light_inverseSurface = Color(0xFF362F2E)
            md_theme_light_inversePrimary = Color(0xFFFFB3AE)
            md_theme_light_shadow = Color(0xFF000000)
            md_theme_light_surfaceTint = Color(0xFFC0001F)

            md_theme_dark_primary = Color(0xFFFFB3AE)
            md_theme_dark_onPrimary = Color(0xFF68000C)
            md_theme_dark_primaryContainer = Color(0xFF930015)
            md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD7)
            md_theme_dark_secondary = Color(0xFFE7BDB9)
            md_theme_dark_onSecondary = Color(0xFF442928)
            md_theme_dark_secondaryContainer = Color(0xFF5D3F3D)
            md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD7)
            md_theme_dark_tertiary = Color(0xFFE2C28C)
            md_theme_dark_onTertiary = Color(0xFF402D04)
            md_theme_dark_tertiaryContainer = Color(0xFF594319)
            md_theme_dark_onTertiaryContainer = Color(0xFFFFDEA7)
            md_theme_dark_error = Color(0xFFFFB4AB)
            md_theme_dark_errorContainer = Color(0xFF93000A)
            md_theme_dark_onError = Color(0xFF690005)
            md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
            md_theme_dark_background = Color(0xFF201A1A)
            md_theme_dark_onBackground = Color(0xFFEDE0DE)
            md_theme_dark_surface = Color(0xFF201A1A)
            md_theme_dark_onSurface = Color(0xFFEDE0DE)
            md_theme_dark_surfaceVariant = Color(0xFF534342)
            md_theme_dark_onSurfaceVariant = Color(0xFFD8C2C0)
            md_theme_dark_outline = Color(0xFFA08C8B)
            md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
            md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
            md_theme_dark_inversePrimary = Color(0xFFC0001F)
            md_theme_dark_shadow = Color(0xFF000000)
            md_theme_dark_surfaceTint = Color(0xFFFFB3AE)


            seed = Color(0xFFDB0025)
        }
        else -> {
        }
    }

    val LightColorScheme = lightColorScheme(
        surfaceTint = md_theme_light_surfaceTint,
        onErrorContainer = md_theme_light_onErrorContainer,
        onError = md_theme_light_onError,
        errorContainer = md_theme_light_errorContainer,
        onTertiaryContainer = md_theme_light_onTertiaryContainer,
        onTertiary = md_theme_light_onTertiary,
        tertiaryContainer = md_theme_light_tertiaryContainer,
        tertiary = md_theme_light_tertiary,
        error = md_theme_light_error,
        outline = md_theme_light_outline,
        onBackground = md_theme_light_onBackground,
        background = md_theme_light_background,
        inverseOnSurface = md_theme_light_inverseOnSurface,
        inverseSurface = md_theme_light_inverseSurface,
        onSurfaceVariant = md_theme_light_onSurfaceVariant,
        onSurface = md_theme_light_onSurface,
        surfaceVariant = md_theme_light_surfaceVariant,
        surface = md_theme_light_surface,
        onSecondaryContainer = md_theme_light_onSecondaryContainer,
        onSecondary = md_theme_light_onSecondary,
        secondaryContainer = md_theme_light_secondaryContainer,
        secondary = md_theme_light_secondary,
        inversePrimary = md_theme_light_inversePrimary,
        onPrimaryContainer = md_theme_light_onPrimaryContainer,
        onPrimary = md_theme_light_onPrimary,
        primaryContainer = md_theme_light_primaryContainer,
        primary = md_theme_light_primary,
    )

    val DarkColorScheme = darkColorScheme(
        surfaceTint = md_theme_dark_surfaceTint,
        onErrorContainer = md_theme_dark_onErrorContainer,
        onError = md_theme_dark_onError,
        errorContainer = md_theme_dark_errorContainer,
        onTertiaryContainer = md_theme_dark_onTertiaryContainer,
        onTertiary = md_theme_dark_onTertiary,
        tertiaryContainer = md_theme_dark_tertiaryContainer,
        tertiary = md_theme_dark_tertiary,
        error = md_theme_dark_error,
        outline = md_theme_dark_outline,
        onBackground = md_theme_dark_onBackground,
        background = md_theme_dark_background,
        inverseOnSurface = md_theme_dark_inverseOnSurface,
        inverseSurface = md_theme_dark_inverseSurface,
        onSurfaceVariant = md_theme_dark_onSurfaceVariant,
        onSurface = md_theme_dark_onSurface,
        surfaceVariant = md_theme_dark_surfaceVariant,
        surface = md_theme_dark_surface,
        onSecondaryContainer = md_theme_dark_onSecondaryContainer,
        onSecondary = md_theme_dark_onSecondary,
        secondaryContainer = md_theme_dark_secondaryContainer,
        secondary = md_theme_dark_secondary,
        inversePrimary = md_theme_dark_inversePrimary,
        onPrimaryContainer = md_theme_dark_onPrimaryContainer,
        onPrimary = md_theme_dark_onPrimary,
        primaryContainer = md_theme_dark_primaryContainer,
        primary = md_theme_dark_primary,
    )

    return arrayOf(LightColorScheme, DarkColorScheme)
}
