// Copyright 2022 Benjamin Meyjohann

package com.example.myapplication.ui.theme

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*

val iconSet = setOf(
    Icons.Filled.AccountBox,
    Icons.Filled.AccountCircle,
    Icons.Filled.Add,
    Icons.Filled.AddCircle,
    Icons.Filled.ArrowBack,
    Icons.Filled.ArrowDropDown,
    Icons.Filled.ArrowForward,
    Icons.Filled.Build,
    Icons.Filled.Call,
    Icons.Filled.Check,
    Icons.Filled.CheckCircle,
    Icons.Filled.Clear,
    Icons.Filled.Close,
    Icons.Filled.Create,
    Icons.Filled.DateRange,
    Icons.Filled.Delete,
    Icons.Filled.Done,
    Icons.Filled.Edit,
    Icons.Filled.Email,
    Icons.Filled.ExitToApp,
    Icons.Filled.Face,
    Icons.Filled.Favorite,
    Icons.Filled.FavoriteBorder,
    Icons.Filled.Home,
    Icons.Filled.Info,
    Icons.Filled.KeyboardArrowDown,
    Icons.Filled.KeyboardArrowLeft,
    Icons.Filled.KeyboardArrowRight,
    Icons.Filled.KeyboardArrowUp,
    Icons.Filled.List,
    Icons.Filled.LocationOn,
    Icons.Filled.Lock,
    Icons.Filled.MailOutline,
    Icons.Filled.Menu,
    Icons.Filled.MoreVert,
    Icons.Filled.Notifications,
    Icons.Filled.Person,
    Icons.Filled.Phone,
    Icons.Filled.Place,
    Icons.Filled.PlayArrow,
    Icons.Filled.Refresh,
    Icons.Filled.Search,
    Icons.Filled.Send,
    Icons.Filled.Settings,
    Icons.Filled.Share,
    Icons.Filled.ShoppingCart,
    Icons.Filled.Star,
    Icons.Filled.ThumbUp,
    Icons.Filled.Warning
)